# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sword/swordProject/RCompiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sword/swordProject/RCompiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sword/swordProject/RCompiler/CMakeFiles /home/sword/swordProject/RCompiler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sword/swordProject/RCompiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named code

# Build rule for target.
code: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 code
.PHONY : code

# fast build rule for target.
code/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/build
.PHONY : code/fast

#=============================================================================
# Target rules for targets named build

# Build rule for target.
build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build
.PHONY : build

# fast build rule for target.
build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/build
.PHONY : build/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

src/IR/IR_node.o: src/IR/IR_node.cpp.o
.PHONY : src/IR/IR_node.o

# target to build an object file
src/IR/IR_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/IR/IR_node.cpp.o
.PHONY : src/IR/IR_node.cpp.o

src/IR/IR_node.i: src/IR/IR_node.cpp.i
.PHONY : src/IR/IR_node.i

# target to preprocess a source file
src/IR/IR_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/IR/IR_node.cpp.i
.PHONY : src/IR/IR_node.cpp.i

src/IR/IR_node.s: src/IR/IR_node.cpp.s
.PHONY : src/IR/IR_node.s

# target to generate assembly for a file
src/IR/IR_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/IR/IR_node.cpp.s
.PHONY : src/IR/IR_node.cpp.s

src/IR/name_allocator.o: src/IR/name_allocator.cpp.o
.PHONY : src/IR/name_allocator.o

# target to build an object file
src/IR/name_allocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/IR/name_allocator.cpp.o
.PHONY : src/IR/name_allocator.cpp.o

src/IR/name_allocator.i: src/IR/name_allocator.cpp.i
.PHONY : src/IR/name_allocator.i

# target to preprocess a source file
src/IR/name_allocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/IR/name_allocator.cpp.i
.PHONY : src/IR/name_allocator.cpp.i

src/IR/name_allocator.s: src/IR/name_allocator.cpp.s
.PHONY : src/IR/name_allocator.s

# target to generate assembly for a file
src/IR/name_allocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/IR/name_allocator.cpp.s
.PHONY : src/IR/name_allocator.cpp.s

src/IR_visitor/printer/IR_printer.o: src/IR_visitor/printer/IR_printer.cpp.o
.PHONY : src/IR_visitor/printer/IR_printer.o

# target to build an object file
src/IR_visitor/printer/IR_printer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/IR_visitor/printer/IR_printer.cpp.o
.PHONY : src/IR_visitor/printer/IR_printer.cpp.o

src/IR_visitor/printer/IR_printer.i: src/IR_visitor/printer/IR_printer.cpp.i
.PHONY : src/IR_visitor/printer/IR_printer.i

# target to preprocess a source file
src/IR_visitor/printer/IR_printer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/IR_visitor/printer/IR_printer.cpp.i
.PHONY : src/IR_visitor/printer/IR_printer.cpp.i

src/IR_visitor/printer/IR_printer.s: src/IR_visitor/printer/IR_printer.cpp.s
.PHONY : src/IR_visitor/printer/IR_printer.s

# target to generate assembly for a file
src/IR_visitor/printer/IR_printer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/IR_visitor/printer/IR_printer.cpp.s
.PHONY : src/IR_visitor/printer/IR_printer.cpp.s

src/common/config.o: src/common/config.cpp.o
.PHONY : src/common/config.o

# target to build an object file
src/common/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/common/config.cpp.o
.PHONY : src/common/config.cpp.o

src/common/config.i: src/common/config.cpp.i
.PHONY : src/common/config.i

# target to preprocess a source file
src/common/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/common/config.cpp.i
.PHONY : src/common/config.cpp.i

src/common/config.s: src/common/config.cpp.s
.PHONY : src/common/config.s

# target to generate assembly for a file
src/common/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/common/config.cpp.s
.PHONY : src/common/config.cpp.s

src/common/error.o: src/common/error.cpp.o
.PHONY : src/common/error.o

# target to build an object file
src/common/error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/common/error.cpp.o
.PHONY : src/common/error.cpp.o

src/common/error.i: src/common/error.cpp.i
.PHONY : src/common/error.i

# target to preprocess a source file
src/common/error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/common/error.cpp.i
.PHONY : src/common/error.cpp.i

src/common/error.s: src/common/error.cpp.s
.PHONY : src/common/error.s

# target to generate assembly for a file
src/common/error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/common/error.cpp.s
.PHONY : src/common/error.cpp.s

src/common/tool_func.o: src/common/tool_func.cpp.o
.PHONY : src/common/tool_func.o

# target to build an object file
src/common/tool_func.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/common/tool_func.cpp.o
.PHONY : src/common/tool_func.cpp.o

src/common/tool_func.i: src/common/tool_func.cpp.i
.PHONY : src/common/tool_func.i

# target to preprocess a source file
src/common/tool_func.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/common/tool_func.cpp.i
.PHONY : src/common/tool_func.cpp.i

src/common/tool_func.s: src/common/tool_func.cpp.s
.PHONY : src/common/tool_func.s

# target to generate assembly for a file
src/common/tool_func.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/common/tool_func.cpp.s
.PHONY : src/common/tool_func.cpp.s

src/data_loader/data_loader.o: src/data_loader/data_loader.cpp.o
.PHONY : src/data_loader/data_loader.o

# target to build an object file
src/data_loader/data_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/data_loader/data_loader.cpp.o
.PHONY : src/data_loader/data_loader.cpp.o

src/data_loader/data_loader.i: src/data_loader/data_loader.cpp.i
.PHONY : src/data_loader/data_loader.i

# target to preprocess a source file
src/data_loader/data_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/data_loader/data_loader.cpp.i
.PHONY : src/data_loader/data_loader.cpp.i

src/data_loader/data_loader.s: src/data_loader/data_loader.cpp.s
.PHONY : src/data_loader/data_loader.s

# target to generate assembly for a file
src/data_loader/data_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/data_loader/data_loader.cpp.s
.PHONY : src/data_loader/data_loader.cpp.s

src/lexer/intermediate.o: src/lexer/intermediate.cpp.o
.PHONY : src/lexer/intermediate.o

# target to build an object file
src/lexer/intermediate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/intermediate.cpp.o
.PHONY : src/lexer/intermediate.cpp.o

src/lexer/intermediate.i: src/lexer/intermediate.cpp.i
.PHONY : src/lexer/intermediate.i

# target to preprocess a source file
src/lexer/intermediate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/intermediate.cpp.i
.PHONY : src/lexer/intermediate.cpp.i

src/lexer/intermediate.s: src/lexer/intermediate.cpp.s
.PHONY : src/lexer/intermediate.s

# target to generate assembly for a file
src/lexer/intermediate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/intermediate.cpp.s
.PHONY : src/lexer/intermediate.cpp.s

src/lexer/lexer.o: src/lexer/lexer.cpp.o
.PHONY : src/lexer/lexer.o

# target to build an object file
src/lexer/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/lexer.cpp.o
.PHONY : src/lexer/lexer.cpp.o

src/lexer/lexer.i: src/lexer/lexer.cpp.i
.PHONY : src/lexer/lexer.i

# target to preprocess a source file
src/lexer/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/lexer.cpp.i
.PHONY : src/lexer/lexer.cpp.i

src/lexer/lexer.s: src/lexer/lexer.cpp.s
.PHONY : src/lexer/lexer.s

# target to generate assembly for a file
src/lexer/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/lexer.cpp.s
.PHONY : src/lexer/lexer.cpp.s

src/lexer/meaningless.o: src/lexer/meaningless.cpp.o
.PHONY : src/lexer/meaningless.o

# target to build an object file
src/lexer/meaningless.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/meaningless.cpp.o
.PHONY : src/lexer/meaningless.cpp.o

src/lexer/meaningless.i: src/lexer/meaningless.cpp.i
.PHONY : src/lexer/meaningless.i

# target to preprocess a source file
src/lexer/meaningless.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/meaningless.cpp.i
.PHONY : src/lexer/meaningless.cpp.i

src/lexer/meaningless.s: src/lexer/meaningless.cpp.s
.PHONY : src/lexer/meaningless.s

# target to generate assembly for a file
src/lexer/meaningless.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/meaningless.cpp.s
.PHONY : src/lexer/meaningless.cpp.s

src/lexer/single.o: src/lexer/single.cpp.o
.PHONY : src/lexer/single.o

# target to build an object file
src/lexer/single.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/single.cpp.o
.PHONY : src/lexer/single.cpp.o

src/lexer/single.i: src/lexer/single.cpp.i
.PHONY : src/lexer/single.i

# target to preprocess a source file
src/lexer/single.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/single.cpp.i
.PHONY : src/lexer/single.cpp.i

src/lexer/single.s: src/lexer/single.cpp.s
.PHONY : src/lexer/single.s

# target to generate assembly for a file
src/lexer/single.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/single.cpp.s
.PHONY : src/lexer/single.cpp.s

src/lexer/token.o: src/lexer/token.cpp.o
.PHONY : src/lexer/token.o

# target to build an object file
src/lexer/token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/token.cpp.o
.PHONY : src/lexer/token.cpp.o

src/lexer/token.i: src/lexer/token.cpp.i
.PHONY : src/lexer/token.i

# target to preprocess a source file
src/lexer/token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/token.cpp.i
.PHONY : src/lexer/token.cpp.i

src/lexer/token.s: src/lexer/token.cpp.s
.PHONY : src/lexer/token.s

# target to generate assembly for a file
src/lexer/token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/lexer/token.cpp.s
.PHONY : src/lexer/token.cpp.s

src/parser/accept.o: src/parser/accept.cpp.o
.PHONY : src/parser/accept.o

# target to build an object file
src/parser/accept.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/accept.cpp.o
.PHONY : src/parser/accept.cpp.o

src/parser/accept.i: src/parser/accept.cpp.i
.PHONY : src/parser/accept.i

# target to preprocess a source file
src/parser/accept.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/accept.cpp.i
.PHONY : src/parser/accept.cpp.i

src/parser/accept.s: src/parser/accept.cpp.s
.PHONY : src/parser/accept.s

# target to generate assembly for a file
src/parser/accept.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/accept.cpp.s
.PHONY : src/parser/accept.cpp.s

src/parser/node/AST_node.o: src/parser/node/AST_node.cpp.o
.PHONY : src/parser/node/AST_node.o

# target to build an object file
src/parser/node/AST_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/AST_node.cpp.o
.PHONY : src/parser/node/AST_node.cpp.o

src/parser/node/AST_node.i: src/parser/node/AST_node.cpp.i
.PHONY : src/parser/node/AST_node.i

# target to preprocess a source file
src/parser/node/AST_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/AST_node.cpp.i
.PHONY : src/parser/node/AST_node.cpp.i

src/parser/node/AST_node.s: src/parser/node/AST_node.cpp.s
.PHONY : src/parser/node/AST_node.s

# target to generate assembly for a file
src/parser/node/AST_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/AST_node.cpp.s
.PHONY : src/parser/node/AST_node.cpp.s

src/parser/node/crate.o: src/parser/node/crate.cpp.o
.PHONY : src/parser/node/crate.o

# target to build an object file
src/parser/node/crate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/crate.cpp.o
.PHONY : src/parser/node/crate.cpp.o

src/parser/node/crate.i: src/parser/node/crate.cpp.i
.PHONY : src/parser/node/crate.i

# target to preprocess a source file
src/parser/node/crate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/crate.cpp.i
.PHONY : src/parser/node/crate.cpp.i

src/parser/node/crate.s: src/parser/node/crate.cpp.s
.PHONY : src/parser/node/crate.s

# target to generate assembly for a file
src/parser/node/crate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/crate.cpp.s
.PHONY : src/parser/node/crate.cpp.s

src/parser/node/enumeration.o: src/parser/node/enumeration.cpp.o
.PHONY : src/parser/node/enumeration.o

# target to build an object file
src/parser/node/enumeration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/enumeration.cpp.o
.PHONY : src/parser/node/enumeration.cpp.o

src/parser/node/enumeration.i: src/parser/node/enumeration.cpp.i
.PHONY : src/parser/node/enumeration.i

# target to preprocess a source file
src/parser/node/enumeration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/enumeration.cpp.i
.PHONY : src/parser/node/enumeration.cpp.i

src/parser/node/enumeration.s: src/parser/node/enumeration.cpp.s
.PHONY : src/parser/node/enumeration.s

# target to generate assembly for a file
src/parser/node/enumeration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/enumeration.cpp.s
.PHONY : src/parser/node/enumeration.cpp.s

src/parser/node/expression.o: src/parser/node/expression.cpp.o
.PHONY : src/parser/node/expression.o

# target to build an object file
src/parser/node/expression.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/expression.cpp.o
.PHONY : src/parser/node/expression.cpp.o

src/parser/node/expression.i: src/parser/node/expression.cpp.i
.PHONY : src/parser/node/expression.i

# target to preprocess a source file
src/parser/node/expression.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/expression.cpp.i
.PHONY : src/parser/node/expression.cpp.i

src/parser/node/expression.s: src/parser/node/expression.cpp.s
.PHONY : src/parser/node/expression.s

# target to generate assembly for a file
src/parser/node/expression.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/expression.cpp.s
.PHONY : src/parser/node/expression.cpp.s

src/parser/node/function.o: src/parser/node/function.cpp.o
.PHONY : src/parser/node/function.o

# target to build an object file
src/parser/node/function.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/function.cpp.o
.PHONY : src/parser/node/function.cpp.o

src/parser/node/function.i: src/parser/node/function.cpp.i
.PHONY : src/parser/node/function.i

# target to preprocess a source file
src/parser/node/function.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/function.cpp.i
.PHONY : src/parser/node/function.cpp.i

src/parser/node/function.s: src/parser/node/function.cpp.s
.PHONY : src/parser/node/function.s

# target to generate assembly for a file
src/parser/node/function.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/function.cpp.s
.PHONY : src/parser/node/function.cpp.s

src/parser/node/implementation.o: src/parser/node/implementation.cpp.o
.PHONY : src/parser/node/implementation.o

# target to build an object file
src/parser/node/implementation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/implementation.cpp.o
.PHONY : src/parser/node/implementation.cpp.o

src/parser/node/implementation.i: src/parser/node/implementation.cpp.i
.PHONY : src/parser/node/implementation.i

# target to preprocess a source file
src/parser/node/implementation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/implementation.cpp.i
.PHONY : src/parser/node/implementation.cpp.i

src/parser/node/implementation.s: src/parser/node/implementation.cpp.s
.PHONY : src/parser/node/implementation.s

# target to generate assembly for a file
src/parser/node/implementation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/implementation.cpp.s
.PHONY : src/parser/node/implementation.cpp.s

src/parser/node/item.o: src/parser/node/item.cpp.o
.PHONY : src/parser/node/item.o

# target to build an object file
src/parser/node/item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/item.cpp.o
.PHONY : src/parser/node/item.cpp.o

src/parser/node/item.i: src/parser/node/item.cpp.i
.PHONY : src/parser/node/item.i

# target to preprocess a source file
src/parser/node/item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/item.cpp.i
.PHONY : src/parser/node/item.cpp.i

src/parser/node/item.s: src/parser/node/item.cpp.s
.PHONY : src/parser/node/item.s

# target to generate assembly for a file
src/parser/node/item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/item.cpp.s
.PHONY : src/parser/node/item.cpp.s

src/parser/node/path.o: src/parser/node/path.cpp.o
.PHONY : src/parser/node/path.o

# target to build an object file
src/parser/node/path.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/path.cpp.o
.PHONY : src/parser/node/path.cpp.o

src/parser/node/path.i: src/parser/node/path.cpp.i
.PHONY : src/parser/node/path.i

# target to preprocess a source file
src/parser/node/path.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/path.cpp.i
.PHONY : src/parser/node/path.cpp.i

src/parser/node/path.s: src/parser/node/path.cpp.s
.PHONY : src/parser/node/path.s

# target to generate assembly for a file
src/parser/node/path.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/path.cpp.s
.PHONY : src/parser/node/path.cpp.s

src/parser/node/pattern.o: src/parser/node/pattern.cpp.o
.PHONY : src/parser/node/pattern.o

# target to build an object file
src/parser/node/pattern.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/pattern.cpp.o
.PHONY : src/parser/node/pattern.cpp.o

src/parser/node/pattern.i: src/parser/node/pattern.cpp.i
.PHONY : src/parser/node/pattern.i

# target to preprocess a source file
src/parser/node/pattern.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/pattern.cpp.i
.PHONY : src/parser/node/pattern.cpp.i

src/parser/node/pattern.s: src/parser/node/pattern.cpp.s
.PHONY : src/parser/node/pattern.s

# target to generate assembly for a file
src/parser/node/pattern.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/pattern.cpp.s
.PHONY : src/parser/node/pattern.cpp.s

src/parser/node/statement.o: src/parser/node/statement.cpp.o
.PHONY : src/parser/node/statement.o

# target to build an object file
src/parser/node/statement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/statement.cpp.o
.PHONY : src/parser/node/statement.cpp.o

src/parser/node/statement.i: src/parser/node/statement.cpp.i
.PHONY : src/parser/node/statement.i

# target to preprocess a source file
src/parser/node/statement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/statement.cpp.i
.PHONY : src/parser/node/statement.cpp.i

src/parser/node/statement.s: src/parser/node/statement.cpp.s
.PHONY : src/parser/node/statement.s

# target to generate assembly for a file
src/parser/node/statement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/statement.cpp.s
.PHONY : src/parser/node/statement.cpp.s

src/parser/node/struct.o: src/parser/node/struct.cpp.o
.PHONY : src/parser/node/struct.o

# target to build an object file
src/parser/node/struct.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/struct.cpp.o
.PHONY : src/parser/node/struct.cpp.o

src/parser/node/struct.i: src/parser/node/struct.cpp.i
.PHONY : src/parser/node/struct.i

# target to preprocess a source file
src/parser/node/struct.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/struct.cpp.i
.PHONY : src/parser/node/struct.cpp.i

src/parser/node/struct.s: src/parser/node/struct.cpp.s
.PHONY : src/parser/node/struct.s

# target to generate assembly for a file
src/parser/node/struct.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/struct.cpp.s
.PHONY : src/parser/node/struct.cpp.s

src/parser/node/terminal.o: src/parser/node/terminal.cpp.o
.PHONY : src/parser/node/terminal.o

# target to build an object file
src/parser/node/terminal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/terminal.cpp.o
.PHONY : src/parser/node/terminal.cpp.o

src/parser/node/terminal.i: src/parser/node/terminal.cpp.i
.PHONY : src/parser/node/terminal.i

# target to preprocess a source file
src/parser/node/terminal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/terminal.cpp.i
.PHONY : src/parser/node/terminal.cpp.i

src/parser/node/terminal.s: src/parser/node/terminal.cpp.s
.PHONY : src/parser/node/terminal.s

# target to generate assembly for a file
src/parser/node/terminal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/terminal.cpp.s
.PHONY : src/parser/node/terminal.cpp.s

src/parser/node/trait.o: src/parser/node/trait.cpp.o
.PHONY : src/parser/node/trait.o

# target to build an object file
src/parser/node/trait.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/trait.cpp.o
.PHONY : src/parser/node/trait.cpp.o

src/parser/node/trait.i: src/parser/node/trait.cpp.i
.PHONY : src/parser/node/trait.i

# target to preprocess a source file
src/parser/node/trait.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/trait.cpp.i
.PHONY : src/parser/node/trait.cpp.i

src/parser/node/trait.s: src/parser/node/trait.cpp.s
.PHONY : src/parser/node/trait.s

# target to generate assembly for a file
src/parser/node/trait.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/trait.cpp.s
.PHONY : src/parser/node/trait.cpp.s

src/parser/node/type.o: src/parser/node/type.cpp.o
.PHONY : src/parser/node/type.o

# target to build an object file
src/parser/node/type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/type.cpp.o
.PHONY : src/parser/node/type.cpp.o

src/parser/node/type.i: src/parser/node/type.cpp.i
.PHONY : src/parser/node/type.i

# target to preprocess a source file
src/parser/node/type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/type.cpp.i
.PHONY : src/parser/node/type.cpp.i

src/parser/node/type.s: src/parser/node/type.cpp.s
.PHONY : src/parser/node/type.s

# target to generate assembly for a file
src/parser/node/type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/parser/node/type.cpp.s
.PHONY : src/parser/node/type.cpp.s

src/semantic/builtin/buildin_node.o: src/semantic/builtin/buildin_node.cpp.o
.PHONY : src/semantic/builtin/buildin_node.o

# target to build an object file
src/semantic/builtin/buildin_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/semantic/builtin/buildin_node.cpp.o
.PHONY : src/semantic/builtin/buildin_node.cpp.o

src/semantic/builtin/buildin_node.i: src/semantic/builtin/buildin_node.cpp.i
.PHONY : src/semantic/builtin/buildin_node.i

# target to preprocess a source file
src/semantic/builtin/buildin_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/semantic/builtin/buildin_node.cpp.i
.PHONY : src/semantic/builtin/buildin_node.cpp.i

src/semantic/builtin/buildin_node.s: src/semantic/builtin/buildin_node.cpp.s
.PHONY : src/semantic/builtin/buildin_node.s

# target to generate assembly for a file
src/semantic/builtin/buildin_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/semantic/builtin/buildin_node.cpp.s
.PHONY : src/semantic/builtin/buildin_node.cpp.s

src/semantic/scope/scope.o: src/semantic/scope/scope.cpp.o
.PHONY : src/semantic/scope/scope.o

# target to build an object file
src/semantic/scope/scope.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/semantic/scope/scope.cpp.o
.PHONY : src/semantic/scope/scope.cpp.o

src/semantic/scope/scope.i: src/semantic/scope/scope.cpp.i
.PHONY : src/semantic/scope/scope.i

# target to preprocess a source file
src/semantic/scope/scope.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/semantic/scope/scope.cpp.i
.PHONY : src/semantic/scope/scope.cpp.i

src/semantic/scope/scope.s: src/semantic/scope/scope.cpp.s
.PHONY : src/semantic/scope/scope.s

# target to generate assembly for a file
src/semantic/scope/scope.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/semantic/scope/scope.cpp.s
.PHONY : src/semantic/scope/scope.cpp.s

src/semantic/type/type.o: src/semantic/type/type.cpp.o
.PHONY : src/semantic/type/type.o

# target to build an object file
src/semantic/type/type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/semantic/type/type.cpp.o
.PHONY : src/semantic/type/type.cpp.o

src/semantic/type/type.i: src/semantic/type/type.cpp.i
.PHONY : src/semantic/type/type.i

# target to preprocess a source file
src/semantic/type/type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/semantic/type/type.cpp.i
.PHONY : src/semantic/type/type.cpp.i

src/semantic/type/type.s: src/semantic/type/type.cpp.s
.PHONY : src/semantic/type/type.s

# target to generate assembly for a file
src/semantic/type/type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/semantic/type/type.cpp.s
.PHONY : src/semantic/type/type.cpp.s

src/visitor/IR_generator/IR_generator.o: src/visitor/IR_generator/IR_generator.cpp.o
.PHONY : src/visitor/IR_generator/IR_generator.o

# target to build an object file
src/visitor/IR_generator/IR_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/IR_generator/IR_generator.cpp.o
.PHONY : src/visitor/IR_generator/IR_generator.cpp.o

src/visitor/IR_generator/IR_generator.i: src/visitor/IR_generator/IR_generator.cpp.i
.PHONY : src/visitor/IR_generator/IR_generator.i

# target to preprocess a source file
src/visitor/IR_generator/IR_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/IR_generator/IR_generator.cpp.i
.PHONY : src/visitor/IR_generator/IR_generator.cpp.i

src/visitor/IR_generator/IR_generator.s: src/visitor/IR_generator/IR_generator.cpp.s
.PHONY : src/visitor/IR_generator/IR_generator.s

# target to generate assembly for a file
src/visitor/IR_generator/IR_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/IR_generator/IR_generator.cpp.s
.PHONY : src/visitor/IR_generator/IR_generator.cpp.s

src/visitor/checker/first_checker.o: src/visitor/checker/first_checker.cpp.o
.PHONY : src/visitor/checker/first_checker.o

# target to build an object file
src/visitor/checker/first_checker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/checker/first_checker.cpp.o
.PHONY : src/visitor/checker/first_checker.cpp.o

src/visitor/checker/first_checker.i: src/visitor/checker/first_checker.cpp.i
.PHONY : src/visitor/checker/first_checker.i

# target to preprocess a source file
src/visitor/checker/first_checker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/checker/first_checker.cpp.i
.PHONY : src/visitor/checker/first_checker.cpp.i

src/visitor/checker/first_checker.s: src/visitor/checker/first_checker.cpp.s
.PHONY : src/visitor/checker/first_checker.s

# target to generate assembly for a file
src/visitor/checker/first_checker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/checker/first_checker.cpp.s
.PHONY : src/visitor/checker/first_checker.cpp.s

src/visitor/checker/second_checker.o: src/visitor/checker/second_checker.cpp.o
.PHONY : src/visitor/checker/second_checker.o

# target to build an object file
src/visitor/checker/second_checker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/checker/second_checker.cpp.o
.PHONY : src/visitor/checker/second_checker.cpp.o

src/visitor/checker/second_checker.i: src/visitor/checker/second_checker.cpp.i
.PHONY : src/visitor/checker/second_checker.i

# target to preprocess a source file
src/visitor/checker/second_checker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/checker/second_checker.cpp.i
.PHONY : src/visitor/checker/second_checker.cpp.i

src/visitor/checker/second_checker.s: src/visitor/checker/second_checker.cpp.s
.PHONY : src/visitor/checker/second_checker.s

# target to generate assembly for a file
src/visitor/checker/second_checker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/checker/second_checker.cpp.s
.PHONY : src/visitor/checker/second_checker.cpp.s

src/visitor/checker/third_checker.o: src/visitor/checker/third_checker.cpp.o
.PHONY : src/visitor/checker/third_checker.o

# target to build an object file
src/visitor/checker/third_checker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/checker/third_checker.cpp.o
.PHONY : src/visitor/checker/third_checker.cpp.o

src/visitor/checker/third_checker.i: src/visitor/checker/third_checker.cpp.i
.PHONY : src/visitor/checker/third_checker.i

# target to preprocess a source file
src/visitor/checker/third_checker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/checker/third_checker.cpp.i
.PHONY : src/visitor/checker/third_checker.cpp.i

src/visitor/checker/third_checker.s: src/visitor/checker/third_checker.cpp.s
.PHONY : src/visitor/checker/third_checker.s

# target to generate assembly for a file
src/visitor/checker/third_checker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/checker/third_checker.cpp.s
.PHONY : src/visitor/checker/third_checker.cpp.s

src/visitor/printer/printer.o: src/visitor/printer/printer.cpp.o
.PHONY : src/visitor/printer/printer.o

# target to build an object file
src/visitor/printer/printer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/printer/printer.cpp.o
.PHONY : src/visitor/printer/printer.cpp.o

src/visitor/printer/printer.i: src/visitor/printer/printer.cpp.i
.PHONY : src/visitor/printer/printer.i

# target to preprocess a source file
src/visitor/printer/printer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/printer/printer.cpp.i
.PHONY : src/visitor/printer/printer.cpp.i

src/visitor/printer/printer.s: src/visitor/printer/printer.cpp.s
.PHONY : src/visitor/printer/printer.s

# target to generate assembly for a file
src/visitor/printer/printer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/visitor/printer/printer.cpp.s
.PHONY : src/visitor/printer/printer.cpp.s

test/IR_submit.o: test/IR_submit.cpp.o
.PHONY : test/IR_submit.o

# target to build an object file
test/IR_submit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/test/IR_submit.cpp.o
.PHONY : test/IR_submit.cpp.o

test/IR_submit.i: test/IR_submit.cpp.i
.PHONY : test/IR_submit.i

# target to preprocess a source file
test/IR_submit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/test/IR_submit.cpp.i
.PHONY : test/IR_submit.cpp.i

test/IR_submit.s: test/IR_submit.cpp.s
.PHONY : test/IR_submit.s

# target to generate assembly for a file
test/IR_submit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/test/IR_submit.cpp.s
.PHONY : test/IR_submit.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... build"
	@echo "... clean-all"
	@echo "... run"
	@echo "... code"
	@echo "... src/IR/IR_node.o"
	@echo "... src/IR/IR_node.i"
	@echo "... src/IR/IR_node.s"
	@echo "... src/IR/name_allocator.o"
	@echo "... src/IR/name_allocator.i"
	@echo "... src/IR/name_allocator.s"
	@echo "... src/IR_visitor/printer/IR_printer.o"
	@echo "... src/IR_visitor/printer/IR_printer.i"
	@echo "... src/IR_visitor/printer/IR_printer.s"
	@echo "... src/common/config.o"
	@echo "... src/common/config.i"
	@echo "... src/common/config.s"
	@echo "... src/common/error.o"
	@echo "... src/common/error.i"
	@echo "... src/common/error.s"
	@echo "... src/common/tool_func.o"
	@echo "... src/common/tool_func.i"
	@echo "... src/common/tool_func.s"
	@echo "... src/data_loader/data_loader.o"
	@echo "... src/data_loader/data_loader.i"
	@echo "... src/data_loader/data_loader.s"
	@echo "... src/lexer/intermediate.o"
	@echo "... src/lexer/intermediate.i"
	@echo "... src/lexer/intermediate.s"
	@echo "... src/lexer/lexer.o"
	@echo "... src/lexer/lexer.i"
	@echo "... src/lexer/lexer.s"
	@echo "... src/lexer/meaningless.o"
	@echo "... src/lexer/meaningless.i"
	@echo "... src/lexer/meaningless.s"
	@echo "... src/lexer/single.o"
	@echo "... src/lexer/single.i"
	@echo "... src/lexer/single.s"
	@echo "... src/lexer/token.o"
	@echo "... src/lexer/token.i"
	@echo "... src/lexer/token.s"
	@echo "... src/parser/accept.o"
	@echo "... src/parser/accept.i"
	@echo "... src/parser/accept.s"
	@echo "... src/parser/node/AST_node.o"
	@echo "... src/parser/node/AST_node.i"
	@echo "... src/parser/node/AST_node.s"
	@echo "... src/parser/node/crate.o"
	@echo "... src/parser/node/crate.i"
	@echo "... src/parser/node/crate.s"
	@echo "... src/parser/node/enumeration.o"
	@echo "... src/parser/node/enumeration.i"
	@echo "... src/parser/node/enumeration.s"
	@echo "... src/parser/node/expression.o"
	@echo "... src/parser/node/expression.i"
	@echo "... src/parser/node/expression.s"
	@echo "... src/parser/node/function.o"
	@echo "... src/parser/node/function.i"
	@echo "... src/parser/node/function.s"
	@echo "... src/parser/node/implementation.o"
	@echo "... src/parser/node/implementation.i"
	@echo "... src/parser/node/implementation.s"
	@echo "... src/parser/node/item.o"
	@echo "... src/parser/node/item.i"
	@echo "... src/parser/node/item.s"
	@echo "... src/parser/node/path.o"
	@echo "... src/parser/node/path.i"
	@echo "... src/parser/node/path.s"
	@echo "... src/parser/node/pattern.o"
	@echo "... src/parser/node/pattern.i"
	@echo "... src/parser/node/pattern.s"
	@echo "... src/parser/node/statement.o"
	@echo "... src/parser/node/statement.i"
	@echo "... src/parser/node/statement.s"
	@echo "... src/parser/node/struct.o"
	@echo "... src/parser/node/struct.i"
	@echo "... src/parser/node/struct.s"
	@echo "... src/parser/node/terminal.o"
	@echo "... src/parser/node/terminal.i"
	@echo "... src/parser/node/terminal.s"
	@echo "... src/parser/node/trait.o"
	@echo "... src/parser/node/trait.i"
	@echo "... src/parser/node/trait.s"
	@echo "... src/parser/node/type.o"
	@echo "... src/parser/node/type.i"
	@echo "... src/parser/node/type.s"
	@echo "... src/semantic/builtin/buildin_node.o"
	@echo "... src/semantic/builtin/buildin_node.i"
	@echo "... src/semantic/builtin/buildin_node.s"
	@echo "... src/semantic/scope/scope.o"
	@echo "... src/semantic/scope/scope.i"
	@echo "... src/semantic/scope/scope.s"
	@echo "... src/semantic/type/type.o"
	@echo "... src/semantic/type/type.i"
	@echo "... src/semantic/type/type.s"
	@echo "... src/visitor/IR_generator/IR_generator.o"
	@echo "... src/visitor/IR_generator/IR_generator.i"
	@echo "... src/visitor/IR_generator/IR_generator.s"
	@echo "... src/visitor/checker/first_checker.o"
	@echo "... src/visitor/checker/first_checker.i"
	@echo "... src/visitor/checker/first_checker.s"
	@echo "... src/visitor/checker/second_checker.o"
	@echo "... src/visitor/checker/second_checker.i"
	@echo "... src/visitor/checker/second_checker.s"
	@echo "... src/visitor/checker/third_checker.o"
	@echo "... src/visitor/checker/third_checker.i"
	@echo "... src/visitor/checker/third_checker.s"
	@echo "... src/visitor/printer/printer.o"
	@echo "... src/visitor/printer/printer.i"
	@echo "... src/visitor/printer/printer.s"
	@echo "... test/IR_submit.o"
	@echo "... test/IR_submit.i"
	@echo "... test/IR_submit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

